Repository ouzi-dev/credstash-operator, pull requests merged in 2020-02, with the labels that each got.

#23 feat: add support for renaming secret keys
  README.md
  deploy/crds/credstash.ouzi.tech_credstashsecrets_crd.yaml
  go.mod
  go.sum
  pkg/apis/credstash/v1alpha1/credstashsecret_types.go
  pkg/credstash/credstash_secret_getter.go
Labels: approved, lgtm, size/M

#24 docs: add a bit more docs in the root readme
  README.md
Labels: approved, lgtm, size/M

#25 feat: add an extra printer column for the kubectl output
  Makefile
  deploy/crds/credstash.ouzi.tech_credstashsecrets_crd.yaml
  deploy/helm/credstash-operator/crds/crds.yaml
  pkg/apis/credstash/v1alpha1/credstashsecret_types.go
Labels: approved, lgtm, size/S

#26 docs: Add kubectl output
  README.md
Labels: approved, lgtm, size/S

#30 feat: make sure that the integration with the prometheus operator works
  cmd/manager/main.go
  deploy/crds/credstash.ouzi.tech_v1alpha1_credstashsecret_cr.yaml
  deploy/helm/credstash-operator/Chart.yaml
  deploy/helm/credstash-operator/templates/deployment.yaml
  deploy/helm/credstash-operator/templates/role.yaml
  deploy/role.yaml
  pkg/env/getters.go
  pkg/env/getters_test.go
Labels: approved, lgtm, size/M

#43 fix: add helm supportfor operatorInstance
  README.md
  deploy/helm/credstash-operator/templates/deployment.yaml
  deploy/helm/credstash-operator/values.yaml
Labels: approved, lgtm, size/S

#44 doc: typos in Readme
  README.md
Labels: approved, lgtm, size/XS

#48 fix: make sure we only watch secret objects we're interested in that have the correct labels and add labels to said secrets
  deploy/helm/credstash-operator/templates/deployment.yaml
  deploy/helm/credstash-operator/values.yaml
  pkg/controller/credstashsecret/credstashsecret_controller.go
Labels: approved, lgtm, size/S

#49 fix: change deployment strategy to recreate
  deploy/helm/credstash-operator/templates/deployment.yaml
Labels: approved, lgtm, size/XS

#50 build(deps): Update dependencies
  go.mod
  go.sum
Labels: approved, lgtm, size/L
