Repository ouzi-dev/credstash-operator, pull requests merged in 2020-06, with the labels that each got.

#139 docs: Create Code of conduct
  CODE_OF_CONDUCT.md
Labels: approved, lgtm, size/M

#140 doc: add templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: approved, lgtm, size/L

#146 feat: push chart to helm repo
  .prow.yaml
  Makefile
  README.md
  package.json
Labels: approved, lgtm, size/S

#147 fix: use the correct make var to determine chart version
  Makefile
Labels: approved, lgtm, size/XS
